apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: test
        image: test:local
        command: ["./test"]
      restartPolicy: Never
  backoffLimit: 4
