// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user-service.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	pb "tanken/backend/user/rpc/pb"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DataFetcherServiceName is the fully-qualified name of the DataFetcherService service.
	DataFetcherServiceName = "rpc.DataFetcherService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DataFetcherServiceTestConnectionProcedure is the fully-qualified name of the DataFetcherService's
	// TestConnection RPC.
	DataFetcherServiceTestConnectionProcedure = "/rpc.DataFetcherService/TestConnection"
	// DataFetcherServiceGetUserInfoProcedure is the fully-qualified name of the DataFetcherService's
	// GetUserInfo RPC.
	DataFetcherServiceGetUserInfoProcedure = "/rpc.DataFetcherService/GetUserInfo"
	// DataFetcherServiceSignUpUserProcedure is the fully-qualified name of the DataFetcherService's
	// SignUpUser RPC.
	DataFetcherServiceSignUpUserProcedure = "/rpc.DataFetcherService/SignUpUser"
	// DataFetcherServiceUpdateUserProcedure is the fully-qualified name of the DataFetcherService's
	// UpdateUser RPC.
	DataFetcherServiceUpdateUserProcedure = "/rpc.DataFetcherService/UpdateUser"
	// DataFetcherServiceHardDeleteUserProcedure is the fully-qualified name of the DataFetcherService's
	// HardDeleteUser RPC.
	DataFetcherServiceHardDeleteUserProcedure = "/rpc.DataFetcherService/HardDeleteUser"
	// DataFetcherServiceSoftDeleteUserProcedure is the fully-qualified name of the DataFetcherService's
	// SoftDeleteUser RPC.
	DataFetcherServiceSoftDeleteUserProcedure = "/rpc.DataFetcherService/SoftDeleteUser"
	// DataFetcherServiceGetUserInfoByOAuthProcedure is the fully-qualified name of the
	// DataFetcherService's GetUserInfoByOAuth RPC.
	DataFetcherServiceGetUserInfoByOAuthProcedure = "/rpc.DataFetcherService/GetUserInfoByOAuth"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	dataFetcherServiceServiceDescriptor                  = pb.File_user_service_proto.Services().ByName("DataFetcherService")
	dataFetcherServiceTestConnectionMethodDescriptor     = dataFetcherServiceServiceDescriptor.Methods().ByName("TestConnection")
	dataFetcherServiceGetUserInfoMethodDescriptor        = dataFetcherServiceServiceDescriptor.Methods().ByName("GetUserInfo")
	dataFetcherServiceSignUpUserMethodDescriptor         = dataFetcherServiceServiceDescriptor.Methods().ByName("SignUpUser")
	dataFetcherServiceUpdateUserMethodDescriptor         = dataFetcherServiceServiceDescriptor.Methods().ByName("UpdateUser")
	dataFetcherServiceHardDeleteUserMethodDescriptor     = dataFetcherServiceServiceDescriptor.Methods().ByName("HardDeleteUser")
	dataFetcherServiceSoftDeleteUserMethodDescriptor     = dataFetcherServiceServiceDescriptor.Methods().ByName("SoftDeleteUser")
	dataFetcherServiceGetUserInfoByOAuthMethodDescriptor = dataFetcherServiceServiceDescriptor.Methods().ByName("GetUserInfoByOAuth")
)

// DataFetcherServiceClient is a client for the rpc.DataFetcherService service.
type DataFetcherServiceClient interface {
	TestConnection(context.Context, *connect.Request[pb.TestConnectionRequest]) (*connect.Response[pb.TestConnectionResponse], error)
	GetUserInfo(context.Context, *connect.Request[pb.GetUserInfoRequest]) (*connect.Response[pb.GetUserInfoResponse], error)
	SignUpUser(context.Context, *connect.Request[pb.SignUpUserRequest]) (*connect.Response[pb.SignUpUserResponse], error)
	UpdateUser(context.Context, *connect.Request[pb.UpdateUserRequest]) (*connect.Response[pb.UpdateUserResponse], error)
	HardDeleteUser(context.Context, *connect.Request[pb.HardDeleteUserRequest]) (*connect.Response[pb.HardDeleteUserResponse], error)
	SoftDeleteUser(context.Context, *connect.Request[pb.SoftDeleteUserRequest]) (*connect.Response[pb.SoftDeleteUserResponse], error)
	GetUserInfoByOAuth(context.Context, *connect.Request[pb.GetUserInfoByOAuthRequest]) (*connect.Response[pb.GetUserInfoByOAuthResponse], error)
}

// NewDataFetcherServiceClient constructs a client for the rpc.DataFetcherService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDataFetcherServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DataFetcherServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &dataFetcherServiceClient{
		testConnection: connect.NewClient[pb.TestConnectionRequest, pb.TestConnectionResponse](
			httpClient,
			baseURL+DataFetcherServiceTestConnectionProcedure,
			connect.WithSchema(dataFetcherServiceTestConnectionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getUserInfo: connect.NewClient[pb.GetUserInfoRequest, pb.GetUserInfoResponse](
			httpClient,
			baseURL+DataFetcherServiceGetUserInfoProcedure,
			connect.WithSchema(dataFetcherServiceGetUserInfoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		signUpUser: connect.NewClient[pb.SignUpUserRequest, pb.SignUpUserResponse](
			httpClient,
			baseURL+DataFetcherServiceSignUpUserProcedure,
			connect.WithSchema(dataFetcherServiceSignUpUserMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[pb.UpdateUserRequest, pb.UpdateUserResponse](
			httpClient,
			baseURL+DataFetcherServiceUpdateUserProcedure,
			connect.WithSchema(dataFetcherServiceUpdateUserMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		hardDeleteUser: connect.NewClient[pb.HardDeleteUserRequest, pb.HardDeleteUserResponse](
			httpClient,
			baseURL+DataFetcherServiceHardDeleteUserProcedure,
			connect.WithSchema(dataFetcherServiceHardDeleteUserMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		softDeleteUser: connect.NewClient[pb.SoftDeleteUserRequest, pb.SoftDeleteUserResponse](
			httpClient,
			baseURL+DataFetcherServiceSoftDeleteUserProcedure,
			connect.WithSchema(dataFetcherServiceSoftDeleteUserMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getUserInfoByOAuth: connect.NewClient[pb.GetUserInfoByOAuthRequest, pb.GetUserInfoByOAuthResponse](
			httpClient,
			baseURL+DataFetcherServiceGetUserInfoByOAuthProcedure,
			connect.WithSchema(dataFetcherServiceGetUserInfoByOAuthMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// dataFetcherServiceClient implements DataFetcherServiceClient.
type dataFetcherServiceClient struct {
	testConnection     *connect.Client[pb.TestConnectionRequest, pb.TestConnectionResponse]
	getUserInfo        *connect.Client[pb.GetUserInfoRequest, pb.GetUserInfoResponse]
	signUpUser         *connect.Client[pb.SignUpUserRequest, pb.SignUpUserResponse]
	updateUser         *connect.Client[pb.UpdateUserRequest, pb.UpdateUserResponse]
	hardDeleteUser     *connect.Client[pb.HardDeleteUserRequest, pb.HardDeleteUserResponse]
	softDeleteUser     *connect.Client[pb.SoftDeleteUserRequest, pb.SoftDeleteUserResponse]
	getUserInfoByOAuth *connect.Client[pb.GetUserInfoByOAuthRequest, pb.GetUserInfoByOAuthResponse]
}

// TestConnection calls rpc.DataFetcherService.TestConnection.
func (c *dataFetcherServiceClient) TestConnection(ctx context.Context, req *connect.Request[pb.TestConnectionRequest]) (*connect.Response[pb.TestConnectionResponse], error) {
	return c.testConnection.CallUnary(ctx, req)
}

// GetUserInfo calls rpc.DataFetcherService.GetUserInfo.
func (c *dataFetcherServiceClient) GetUserInfo(ctx context.Context, req *connect.Request[pb.GetUserInfoRequest]) (*connect.Response[pb.GetUserInfoResponse], error) {
	return c.getUserInfo.CallUnary(ctx, req)
}

// SignUpUser calls rpc.DataFetcherService.SignUpUser.
func (c *dataFetcherServiceClient) SignUpUser(ctx context.Context, req *connect.Request[pb.SignUpUserRequest]) (*connect.Response[pb.SignUpUserResponse], error) {
	return c.signUpUser.CallUnary(ctx, req)
}

// UpdateUser calls rpc.DataFetcherService.UpdateUser.
func (c *dataFetcherServiceClient) UpdateUser(ctx context.Context, req *connect.Request[pb.UpdateUserRequest]) (*connect.Response[pb.UpdateUserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// HardDeleteUser calls rpc.DataFetcherService.HardDeleteUser.
func (c *dataFetcherServiceClient) HardDeleteUser(ctx context.Context, req *connect.Request[pb.HardDeleteUserRequest]) (*connect.Response[pb.HardDeleteUserResponse], error) {
	return c.hardDeleteUser.CallUnary(ctx, req)
}

// SoftDeleteUser calls rpc.DataFetcherService.SoftDeleteUser.
func (c *dataFetcherServiceClient) SoftDeleteUser(ctx context.Context, req *connect.Request[pb.SoftDeleteUserRequest]) (*connect.Response[pb.SoftDeleteUserResponse], error) {
	return c.softDeleteUser.CallUnary(ctx, req)
}

// GetUserInfoByOAuth calls rpc.DataFetcherService.GetUserInfoByOAuth.
func (c *dataFetcherServiceClient) GetUserInfoByOAuth(ctx context.Context, req *connect.Request[pb.GetUserInfoByOAuthRequest]) (*connect.Response[pb.GetUserInfoByOAuthResponse], error) {
	return c.getUserInfoByOAuth.CallUnary(ctx, req)
}

// DataFetcherServiceHandler is an implementation of the rpc.DataFetcherService service.
type DataFetcherServiceHandler interface {
	TestConnection(context.Context, *connect.Request[pb.TestConnectionRequest]) (*connect.Response[pb.TestConnectionResponse], error)
	GetUserInfo(context.Context, *connect.Request[pb.GetUserInfoRequest]) (*connect.Response[pb.GetUserInfoResponse], error)
	SignUpUser(context.Context, *connect.Request[pb.SignUpUserRequest]) (*connect.Response[pb.SignUpUserResponse], error)
	UpdateUser(context.Context, *connect.Request[pb.UpdateUserRequest]) (*connect.Response[pb.UpdateUserResponse], error)
	HardDeleteUser(context.Context, *connect.Request[pb.HardDeleteUserRequest]) (*connect.Response[pb.HardDeleteUserResponse], error)
	SoftDeleteUser(context.Context, *connect.Request[pb.SoftDeleteUserRequest]) (*connect.Response[pb.SoftDeleteUserResponse], error)
	GetUserInfoByOAuth(context.Context, *connect.Request[pb.GetUserInfoByOAuthRequest]) (*connect.Response[pb.GetUserInfoByOAuthResponse], error)
}

// NewDataFetcherServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDataFetcherServiceHandler(svc DataFetcherServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dataFetcherServiceTestConnectionHandler := connect.NewUnaryHandler(
		DataFetcherServiceTestConnectionProcedure,
		svc.TestConnection,
		connect.WithSchema(dataFetcherServiceTestConnectionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dataFetcherServiceGetUserInfoHandler := connect.NewUnaryHandler(
		DataFetcherServiceGetUserInfoProcedure,
		svc.GetUserInfo,
		connect.WithSchema(dataFetcherServiceGetUserInfoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dataFetcherServiceSignUpUserHandler := connect.NewUnaryHandler(
		DataFetcherServiceSignUpUserProcedure,
		svc.SignUpUser,
		connect.WithSchema(dataFetcherServiceSignUpUserMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dataFetcherServiceUpdateUserHandler := connect.NewUnaryHandler(
		DataFetcherServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(dataFetcherServiceUpdateUserMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dataFetcherServiceHardDeleteUserHandler := connect.NewUnaryHandler(
		DataFetcherServiceHardDeleteUserProcedure,
		svc.HardDeleteUser,
		connect.WithSchema(dataFetcherServiceHardDeleteUserMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dataFetcherServiceSoftDeleteUserHandler := connect.NewUnaryHandler(
		DataFetcherServiceSoftDeleteUserProcedure,
		svc.SoftDeleteUser,
		connect.WithSchema(dataFetcherServiceSoftDeleteUserMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dataFetcherServiceGetUserInfoByOAuthHandler := connect.NewUnaryHandler(
		DataFetcherServiceGetUserInfoByOAuthProcedure,
		svc.GetUserInfoByOAuth,
		connect.WithSchema(dataFetcherServiceGetUserInfoByOAuthMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpc.DataFetcherService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DataFetcherServiceTestConnectionProcedure:
			dataFetcherServiceTestConnectionHandler.ServeHTTP(w, r)
		case DataFetcherServiceGetUserInfoProcedure:
			dataFetcherServiceGetUserInfoHandler.ServeHTTP(w, r)
		case DataFetcherServiceSignUpUserProcedure:
			dataFetcherServiceSignUpUserHandler.ServeHTTP(w, r)
		case DataFetcherServiceUpdateUserProcedure:
			dataFetcherServiceUpdateUserHandler.ServeHTTP(w, r)
		case DataFetcherServiceHardDeleteUserProcedure:
			dataFetcherServiceHardDeleteUserHandler.ServeHTTP(w, r)
		case DataFetcherServiceSoftDeleteUserProcedure:
			dataFetcherServiceSoftDeleteUserHandler.ServeHTTP(w, r)
		case DataFetcherServiceGetUserInfoByOAuthProcedure:
			dataFetcherServiceGetUserInfoByOAuthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDataFetcherServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDataFetcherServiceHandler struct{}

func (UnimplementedDataFetcherServiceHandler) TestConnection(context.Context, *connect.Request[pb.TestConnectionRequest]) (*connect.Response[pb.TestConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.DataFetcherService.TestConnection is not implemented"))
}

func (UnimplementedDataFetcherServiceHandler) GetUserInfo(context.Context, *connect.Request[pb.GetUserInfoRequest]) (*connect.Response[pb.GetUserInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.DataFetcherService.GetUserInfo is not implemented"))
}

func (UnimplementedDataFetcherServiceHandler) SignUpUser(context.Context, *connect.Request[pb.SignUpUserRequest]) (*connect.Response[pb.SignUpUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.DataFetcherService.SignUpUser is not implemented"))
}

func (UnimplementedDataFetcherServiceHandler) UpdateUser(context.Context, *connect.Request[pb.UpdateUserRequest]) (*connect.Response[pb.UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.DataFetcherService.UpdateUser is not implemented"))
}

func (UnimplementedDataFetcherServiceHandler) HardDeleteUser(context.Context, *connect.Request[pb.HardDeleteUserRequest]) (*connect.Response[pb.HardDeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.DataFetcherService.HardDeleteUser is not implemented"))
}

func (UnimplementedDataFetcherServiceHandler) SoftDeleteUser(context.Context, *connect.Request[pb.SoftDeleteUserRequest]) (*connect.Response[pb.SoftDeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.DataFetcherService.SoftDeleteUser is not implemented"))
}

func (UnimplementedDataFetcherServiceHandler) GetUserInfoByOAuth(context.Context, *connect.Request[pb.GetUserInfoByOAuthRequest]) (*connect.Response[pb.GetUserInfoByOAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.DataFetcherService.GetUserInfoByOAuth is not implemented"))
}
