apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-config
data:
  flyway.conf: |
    flyway.url=jdbc:postgresql://database-service:5432/postgres
    flyway.user=postgres
    flyway.password=password
    flyway.schemas=public
    flyway.locations=filesystem:/flyway/migrations