apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration-job
spec:
  template:
    spec:
      containers:
      - name: flyway-migration
        image: flyway/flyway:latest
        command: ["flyway", "migrate"]
        volumeMounts:
        - name: flyway-config-volume
          mountPath: /flyway/conf
        - name: flyway-sql-volume
          mountPath: /flyway/migration
        env:
        - name: FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: flyway.url
        - name: FLYWAY_USER
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: flyway.user
        - name: FLYWAY_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: flyway-config
              key: flyway.password
        - name: FLYWAY_CONFIG_FILES
          value: /flyway/conf
      restartPolicy: OnFailure
      volumes:
      - name: flyway-conf-volume
        hostPath:
          path: ../database/flyway
          type: Directory
      - name: flyway-sql-volume
        hostPath:
          path: ../database/migrations
          type: Directory
