apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
spec:
  selector:
    matchLabels:
      app: data-fetcher
  replicas: 1
  template:
    metadata:
      labels:
        app: data-fetcher
    spec:
      containers:
      - name: data-fetcher
        image: data-fetcher:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: AWS_REGION
          value: "ap-northeast-1"
        - name: POSTGRES_HOST
          value: "database-service"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_SSLMODE
          value: "disable"
        - name: POSTGRES_DBNAME
          value: "postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: data-fetcher
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc
  selector:
    app: data-fetcher
