// @generated by protoc-gen-es v1.9.0 with parameter "target=ts"
// @generated from file comment.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Comment } from "./general_pb.js";

/**
 * @generated from message rpc.AddCommentRequest
 */
export class AddCommentRequest extends Message<AddCommentRequest> {
  /**
   * @generated from field: string userId = 1;
   */
  userId = "";

  /**
   * @generated from field: string postId = 2;
   */
  postId = "";

  /**
   * @generated from field: string content = 3;
   */
  content = "";

  constructor(data?: PartialMessage<AddCommentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.AddCommentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "userId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "postId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddCommentRequest {
    return new AddCommentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddCommentRequest {
    return new AddCommentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddCommentRequest {
    return new AddCommentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AddCommentRequest | PlainMessage<AddCommentRequest> | undefined, b: AddCommentRequest | PlainMessage<AddCommentRequest> | undefined): boolean {
    return proto3.util.equals(AddCommentRequest, a, b);
  }
}

/**
 * @generated from message rpc.AddCommentResponse
 */
export class AddCommentResponse extends Message<AddCommentResponse> {
  /**
   * @generated from field: int64 ok = 1;
   */
  ok = protoInt64.zero;

  /**
   * @generated from field: string msg = 2;
   */
  msg = "";

  /**
   * @generated from field: string commentId = 3;
   */
  commentId = "";

  constructor(data?: PartialMessage<AddCommentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.AddCommentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ok", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "commentId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddCommentResponse {
    return new AddCommentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddCommentResponse {
    return new AddCommentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddCommentResponse {
    return new AddCommentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AddCommentResponse | PlainMessage<AddCommentResponse> | undefined, b: AddCommentResponse | PlainMessage<AddCommentResponse> | undefined): boolean {
    return proto3.util.equals(AddCommentResponse, a, b);
  }
}

/**
 * @generated from message rpc.RemoveCommentRequest
 */
export class RemoveCommentRequest extends Message<RemoveCommentRequest> {
  /**
   * @generated from field: string userId = 1;
   */
  userId = "";

  /**
   * @generated from field: string postId = 2;
   */
  postId = "";

  /**
   * @generated from field: string commentId = 3;
   */
  commentId = "";

  constructor(data?: PartialMessage<RemoveCommentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.RemoveCommentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "userId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "postId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "commentId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveCommentRequest {
    return new RemoveCommentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveCommentRequest {
    return new RemoveCommentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveCommentRequest {
    return new RemoveCommentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveCommentRequest | PlainMessage<RemoveCommentRequest> | undefined, b: RemoveCommentRequest | PlainMessage<RemoveCommentRequest> | undefined): boolean {
    return proto3.util.equals(RemoveCommentRequest, a, b);
  }
}

/**
 * @generated from message rpc.RemoveCommentResponse
 */
export class RemoveCommentResponse extends Message<RemoveCommentResponse> {
  /**
   * @generated from field: int64 ok = 1;
   */
  ok = protoInt64.zero;

  /**
   * @generated from field: string msg = 2;
   */
  msg = "";

  constructor(data?: PartialMessage<RemoveCommentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.RemoveCommentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ok", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveCommentResponse {
    return new RemoveCommentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveCommentResponse {
    return new RemoveCommentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveCommentResponse {
    return new RemoveCommentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveCommentResponse | PlainMessage<RemoveCommentResponse> | undefined, b: RemoveCommentResponse | PlainMessage<RemoveCommentResponse> | undefined): boolean {
    return proto3.util.equals(RemoveCommentResponse, a, b);
  }
}

/**
 * @generated from message rpc.GetCommentsByCommentIdsRequest
 */
export class GetCommentsByCommentIdsRequest extends Message<GetCommentsByCommentIdsRequest> {
  /**
   * @generated from field: repeated string commentId = 1;
   */
  commentId: string[] = [];

  constructor(data?: PartialMessage<GetCommentsByCommentIdsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.GetCommentsByCommentIdsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "commentId", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCommentsByCommentIdsRequest {
    return new GetCommentsByCommentIdsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCommentsByCommentIdsRequest {
    return new GetCommentsByCommentIdsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCommentsByCommentIdsRequest {
    return new GetCommentsByCommentIdsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetCommentsByCommentIdsRequest | PlainMessage<GetCommentsByCommentIdsRequest> | undefined, b: GetCommentsByCommentIdsRequest | PlainMessage<GetCommentsByCommentIdsRequest> | undefined): boolean {
    return proto3.util.equals(GetCommentsByCommentIdsRequest, a, b);
  }
}

/**
 * @generated from message rpc.GetCommentsByCommentIdsResponse
 */
export class GetCommentsByCommentIdsResponse extends Message<GetCommentsByCommentIdsResponse> {
  /**
   * @generated from field: int64 ok = 1;
   */
  ok = protoInt64.zero;

  /**
   * @generated from field: string msg = 2;
   */
  msg = "";

  /**
   * @generated from field: repeated rpc.Comment comment = 3;
   */
  comment: Comment[] = [];

  constructor(data?: PartialMessage<GetCommentsByCommentIdsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.GetCommentsByCommentIdsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ok", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "comment", kind: "message", T: Comment, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCommentsByCommentIdsResponse {
    return new GetCommentsByCommentIdsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCommentsByCommentIdsResponse {
    return new GetCommentsByCommentIdsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCommentsByCommentIdsResponse {
    return new GetCommentsByCommentIdsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetCommentsByCommentIdsResponse | PlainMessage<GetCommentsByCommentIdsResponse> | undefined, b: GetCommentsByCommentIdsResponse | PlainMessage<GetCommentsByCommentIdsResponse> | undefined): boolean {
    return proto3.util.equals(GetCommentsByCommentIdsResponse, a, b);
  }
}

/**
 * @generated from message rpc.GetCommentsByPostIdRequest
 */
export class GetCommentsByPostIdRequest extends Message<GetCommentsByPostIdRequest> {
  /**
   * @generated from field: string postId = 1;
   */
  postId = "";

  constructor(data?: PartialMessage<GetCommentsByPostIdRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.GetCommentsByPostIdRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "postId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCommentsByPostIdRequest {
    return new GetCommentsByPostIdRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCommentsByPostIdRequest {
    return new GetCommentsByPostIdRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCommentsByPostIdRequest {
    return new GetCommentsByPostIdRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetCommentsByPostIdRequest | PlainMessage<GetCommentsByPostIdRequest> | undefined, b: GetCommentsByPostIdRequest | PlainMessage<GetCommentsByPostIdRequest> | undefined): boolean {
    return proto3.util.equals(GetCommentsByPostIdRequest, a, b);
  }
}

/**
 * @generated from message rpc.GetCommentsByPostIdResponse
 */
export class GetCommentsByPostIdResponse extends Message<GetCommentsByPostIdResponse> {
  /**
   * @generated from field: int64 ok = 1;
   */
  ok = protoInt64.zero;

  /**
   * @generated from field: string msg = 2;
   */
  msg = "";

  /**
   * @generated from field: repeated rpc.Comment comments = 3;
   */
  comments: Comment[] = [];

  constructor(data?: PartialMessage<GetCommentsByPostIdResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.GetCommentsByPostIdResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ok", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "comments", kind: "message", T: Comment, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCommentsByPostIdResponse {
    return new GetCommentsByPostIdResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCommentsByPostIdResponse {
    return new GetCommentsByPostIdResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCommentsByPostIdResponse {
    return new GetCommentsByPostIdResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetCommentsByPostIdResponse | PlainMessage<GetCommentsByPostIdResponse> | undefined, b: GetCommentsByPostIdResponse | PlainMessage<GetCommentsByPostIdResponse> | undefined): boolean {
    return proto3.util.equals(GetCommentsByPostIdResponse, a, b);
  }
}

/**
 * @generated from message rpc.ModifyCommentRequest
 */
export class ModifyCommentRequest extends Message<ModifyCommentRequest> {
  /**
   * @generated from field: string userId = 1;
   */
  userId = "";

  /**
   * @generated from field: string commentId = 2;
   */
  commentId = "";

  constructor(data?: PartialMessage<ModifyCommentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.ModifyCommentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "userId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "commentId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModifyCommentRequest {
    return new ModifyCommentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModifyCommentRequest {
    return new ModifyCommentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModifyCommentRequest {
    return new ModifyCommentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ModifyCommentRequest | PlainMessage<ModifyCommentRequest> | undefined, b: ModifyCommentRequest | PlainMessage<ModifyCommentRequest> | undefined): boolean {
    return proto3.util.equals(ModifyCommentRequest, a, b);
  }
}

/**
 * @generated from message rpc.ModifyCommentResponse
 */
export class ModifyCommentResponse extends Message<ModifyCommentResponse> {
  /**
   * @generated from field: int64 ok = 1;
   */
  ok = protoInt64.zero;

  /**
   * @generated from field: string msg = 2;
   */
  msg = "";

  constructor(data?: PartialMessage<ModifyCommentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "rpc.ModifyCommentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ok", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModifyCommentResponse {
    return new ModifyCommentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModifyCommentResponse {
    return new ModifyCommentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModifyCommentResponse {
    return new ModifyCommentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ModifyCommentResponse | PlainMessage<ModifyCommentResponse> | undefined, b: ModifyCommentResponse | PlainMessage<ModifyCommentResponse> | undefined): boolean {
    return proto3.util.equals(ModifyCommentResponse, a, b);
  }
}

