// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file data-fetcher-service.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { TestConnectionRequest, TestConnectionResponse } from "./data-fetcher-service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { AddBookmarkRequest, AddBookmarkResponse, AddCommentRequest, AddCommentResponse, AddLikeRequest, AddLikeResponse, AddPostRequest, AddPostResponse, GetPostsByLocationRequest, GetPostsByLocationResponse, GetPostsByPostIdsRequest, GetPostsByPostIdsResponse, GetPostsByUserIdRequest, GetPostsByUserIdResponse, HardDeletePostRequest, HardDeletePostResponse, RemoveBookmarkRequest, RemoveBookmarkResponse, RemoveCommentRequest, RemoveCommentResponse, RemoveLikeRequest, RemoveLikeResponse, SoftDeletePostRequest, SoftDeletePostResponse } from "./post_pb.js";
import { GetUserInfoByOAuthRequest, GetUserInfoByOAuthResponse, GetUserInfoRequest, GetUserInfoResponse, HardDeleteUserRequest, HardDeleteUserResponse, SignUpUserRequest, SignUpUserResponse, SoftDeleteUserRequest, SoftDeleteUserResponse, UpdateUserRequest, UpdateUserResponse } from "./user_pb.js";

/**
 * @generated from service rpc.DataFetcherService
 */
export const DataFetcherService = {
  typeName: "rpc.DataFetcherService",
  methods: {
    /**
     * @generated from rpc rpc.DataFetcherService.TestConnection
     */
    testConnection: {
      name: "TestConnection",
      I: TestConnectionRequest,
      O: TestConnectionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.GetPostsByLocation
     */
    getPostsByLocation: {
      name: "GetPostsByLocation",
      I: GetPostsByLocationRequest,
      O: GetPostsByLocationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.GetPostsByPostIds
     */
    getPostsByPostIds: {
      name: "GetPostsByPostIds",
      I: GetPostsByPostIdsRequest,
      O: GetPostsByPostIdsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.GetPostsByUser
     */
    getPostsByUser: {
      name: "GetPostsByUser",
      I: GetPostsByUserIdRequest,
      O: GetPostsByUserIdResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.AddPost
     */
    addPost: {
      name: "AddPost",
      I: AddPostRequest,
      O: AddPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.HardDeletePost
     */
    hardDeletePost: {
      name: "HardDeletePost",
      I: HardDeletePostRequest,
      O: HardDeletePostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.SoftDeletePost
     */
    softDeletePost: {
      name: "SoftDeletePost",
      I: SoftDeletePostRequest,
      O: SoftDeletePostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.AddLike
     */
    addLike: {
      name: "AddLike",
      I: AddLikeRequest,
      O: AddLikeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.RemoveLike
     */
    removeLike: {
      name: "RemoveLike",
      I: RemoveLikeRequest,
      O: RemoveLikeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.AddBookmark
     */
    addBookmark: {
      name: "AddBookmark",
      I: AddBookmarkRequest,
      O: AddBookmarkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.RemoveBookmark
     */
    removeBookmark: {
      name: "RemoveBookmark",
      I: RemoveBookmarkRequest,
      O: RemoveBookmarkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.AddComment
     */
    addComment: {
      name: "AddComment",
      I: AddCommentRequest,
      O: AddCommentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.RemoveComment
     */
    removeComment: {
      name: "RemoveComment",
      I: RemoveCommentRequest,
      O: RemoveCommentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.GetUserInfo
     */
    getUserInfo: {
      name: "GetUserInfo",
      I: GetUserInfoRequest,
      O: GetUserInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.SignUpUser
     */
    signUpUser: {
      name: "SignUpUser",
      I: SignUpUserRequest,
      O: SignUpUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: UpdateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.HardDeleteUser
     */
    hardDeleteUser: {
      name: "HardDeleteUser",
      I: HardDeleteUserRequest,
      O: HardDeleteUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.SoftDeleteUser
     */
    softDeleteUser: {
      name: "SoftDeleteUser",
      I: SoftDeleteUserRequest,
      O: SoftDeleteUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rpc.DataFetcherService.GetUserInfoByOAuth
     */
    getUserInfoByOAuth: {
      name: "GetUserInfoByOAuth",
      I: GetUserInfoByOAuthRequest,
      O: GetUserInfoByOAuthResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

